
package jaxws.ping;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PingPort", targetNamespace = "urn:tk.org:ws:common:ping")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PingPort {


    /**
     * 
     * @param soapHeader
     * @param pingRequestIn
     * @return
     *     returns jaxws2.ping.PingResponse
     */
    @WebMethod
    @WebResult(name = "pingResponse", targetNamespace = "urn:tk.org:ws:common:ping", partName = "pingResponse")
    public PingResponse ping(
            @WebParam(name = "PingInputArgs", targetNamespace = "urn:tk.org:ws:common:ping", partName = "PingRequestIn")
                    PingRequest pingRequestIn,
            @WebParam(name = "AuthHeader", targetNamespace = "http://tk.org/header/AuthConfig_v10", header = true, partName = "SoapHeader")
                    AuthHeaderType soapHeader);

}
