
package jaxws.ping;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PingService", targetNamespace = "urn:tk.org:ws:common:ping", wsdlLocation = "file:/D:/WORKSPACE_2018/webservice.teach/jaxws/test/wsdl/Ping.wsdl")
public class PingService
    extends Service
{

    private final static URL PINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException PINGSERVICE_EXCEPTION;
    private final static QName PINGSERVICE_QNAME = new QName("urn:tk.org:ws:common:ping", "PingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/WORKSPACE_2018/webservice.teach/jaxws/test/wsdl/Ping.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PINGSERVICE_WSDL_LOCATION = url;
        PINGSERVICE_EXCEPTION = e;
    }

    public PingService() {
        super(__getWsdlLocation(), PINGSERVICE_QNAME);
    }

    public PingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PINGSERVICE_QNAME, features);
    }

    public PingService(URL wsdlLocation) {
        super(wsdlLocation, PINGSERVICE_QNAME);
    }

    public PingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PINGSERVICE_QNAME, features);
    }

    public PingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PingPort
     */
    @WebEndpoint(name = "PingService")
    public PingPort getPingService() {
        return super.getPort(new QName("urn:tk.org:ws:common:ping", "PingService"), PingPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PingPort
     */
    @WebEndpoint(name = "PingService")
    public PingPort getPingService(WebServiceFeature... features) {
        return super.getPort(new QName("urn:tk.org:ws:common:ping", "PingService"), PingPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PINGSERVICE_EXCEPTION!= null) {
            throw PINGSERVICE_EXCEPTION;
        }
        return PINGSERVICE_WSDL_LOCATION;
    }

}
